[package]
name = "insertion-sort-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.22", features = ["derive"] }

[[bin]]
name = "insertion-sort"
path = "src/main.rs"